# visit http://localhost:8086/
version: '3.9'
services:
  # Telegraf
  telegraf:
    env_file: ./influxdb/env.env
    hostname: telegraf
    image: telegraf:1.21.2
    ports:
      - "8092:8092/udp"
    volumes:
      - ./telegraf/:/etc/telegraf
    depends_on:
      - influxdb
  # InfluxDB
  influxdb:
    env_file: ./influxdb/env.env
    hostname: influxdb
    image: influxdb:2.1
    volumes:
      - ./influxdb/data:/var/lib/influxdb
    stdin_open: true
    tty: true
    ports:
      - 8086:8086

